name: CI-CD

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Speeds up the builds
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      # Run install
      - uses: php-actions/composer@v5
        with:
          dev: yes
          args: --no-interaction --prefer-dist --optimize-autoloader

      # Run linting to make sure it is worthwhile before NPM
      - name: phpstan
        run: |
          ./vendor/bin/phpstan analyse

      # Again another lint before we do the js build
      - name: PHP Code Style (phpcs)
        uses: chindit/actions-phpcs@master
        with:
          # Folder to check code style
          dir: app/
