name: CI-CD

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Speeds up the builds
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      # Run install
      - uses: php-actions/composer@v5with:
        with:
          dev: yes
          args: --no-interaction --prefer-dist --optimize-autoloader
